FROM python:3.12-slim-bookworm
RUN apt-get update && apt-get install -y python3-venv

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the project into the image
ADD test_flag_train.py pyproject.toml /app

# Sync the project into a new environment, asserting the lockfile is up to date
WORKDIR /app
RUN uv sync --locked

# Presuming there is a `my_app` command provided by the project
CMD ["uv", "run", "test_flag_train.py"]
