apiVersion: apps/v1
kind: Deployment
metadata:
  name: dedect-flags
  namespace: default
  labels:
    app: dedect-flags
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-flask-api
  template:
    metadata:
      labels:
        app: yolo-flask-api
        version: v1
    spec:
      containers:
      - name: yolo-flask-api
        image: yolo-flask-api-cuda124:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: MODEL_PATH
          value: "flags.pt"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: dedect-flags
  namespace: default
  labels:
    app: dedect-flags
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: dedect-flags
